### ISSUE TITLE
helm-charts README

### ISSUE THREAD

**Issue by jldec** [projectriff/helm-charts#1]
Riff developers should be able to follow instructions in the helm-charts README.md in order to deploy a full / manual build using helm.

They should also be able to use the helm chart to deploy tagged projectriff images from docker.

**Comment by markfisher** [comment]
I've created the README for now with a one-liner that supports a local install.

**Comment by trisberg** [comment]
I updated the README in https://github.com/projectriff/helm-charts/pull/6

Any specific override instructions for manual development use belong in riff IMO, trying to keep the charts close to the `kubernetes/charts` style do we can move this chart there when we are ready

**Comment by markfisher** [comment]
I agree, and I think the riff Getting Started guide PR should now satisfy those requirements. @jldec have a look: https://github.com/projectriff/riff/pull/187
